package com.argus.controlcenter.identity;

import com.argus.controlcenter.vo.ApiResponse;
import java.util.List;
import java.util.Set;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.web.bind.annotation.*;

/** 项目成员变更；仅项目管理员或平台管理员可写，版本冲突不静默覆盖。 */
@RestController
@RequestMapping("/api/projects/{projectId}/members")
public class ProjectMemberController {
    private final JdbcTemplate jdbc; private final CurrentActorProvider actors; private final ProjectAuthorization auth; private final TransactionTemplate tx;
    public ProjectMemberController(JdbcTemplate jdbc,CurrentActorProvider actors,ProjectAuthorization auth,PlatformTransactionManager manager){this.jdbc=jdbc;this.actors=actors;this.auth=auth;this.tx=new TransactionTemplate(manager);}
    @GetMapping public ApiResponse<List<MemberView>> list(@PathVariable String projectId){CurrentActor a=actors.requireCurrent();auth.require(a,projectId,ProjectPermission.MEMBER_MANAGE);return ApiResponse.ok(jdbc.query("SELECT u.id,u.display_name,u.status,pm.role,pm.version_no FROM project_members pm JOIN users u ON u.id=pm.user_id WHERE pm.project_id=? ORDER BY u.id",(r,n)->new MemberView(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getLong(5)),projectId));}
    @PutMapping("/{userId}") public ApiResponse<MemberView> put(@PathVariable String projectId,@PathVariable String userId,@RequestBody MemberChange body){CurrentActor a=actors.requireCurrent();if(body==null||body.role()==null||body.expectedVersion()<0||!Set.of("ADMIN","OPERATOR","VIEWER").contains(body.role()))throw bad();return ApiResponse.ok(tx.execute(s->{lockGate();auth.requireForUpdate(a.userId(),a.authMode(),projectId,ProjectPermission.MEMBER_MANAGE);List<String> oldRoles=jdbc.queryForList("SELECT role FROM project_members WHERE project_id=? AND user_id=?",String.class,projectId,userId);String oldRole=oldRoles.isEmpty()?null:oldRoles.get(0);if(oldRole!=null&&"ADMIN".equals(oldRole)&&!"ADMIN".equals(body.role())&&jdbc.queryForObject("SELECT COUNT(*) FROM project_members WHERE project_id=? AND role='ADMIN'",Long.class,projectId)<=1)throw new IdentityAuthorizationException("LAST_PROJECT_ADMIN",409);int exists=jdbc.update("UPDATE project_members SET role=?,version_no=version_no+1,updated_at=CURRENT_TIMESTAMP WHERE project_id=? AND user_id=? AND version_no=?",body.role(),projectId,userId,body.expectedVersion());if(exists==0&&(oldRole!=null||body.expectedVersion()!=0))throw new IdentityAuthorizationException("VERSION_CONFLICT",409);if(exists==0){int active=jdbc.update("UPDATE users SET version_no=version_no WHERE id=? AND status='ACTIVE'",userId);if(active!=1)throw new IdentityAuthorizationException("RESOURCE_NOT_FOUND",404);jdbc.update("INSERT INTO project_members(project_id,user_id,role,version_no,created_at,updated_at) VALUES(?,?,?,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",projectId,userId,body.role());}jdbc.update("UPDATE projects SET permission_version=permission_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?",projectId);return one(projectId,userId);}));}
    @DeleteMapping("/{userId}") public ApiResponse<Void> remove(@PathVariable String projectId,@PathVariable String userId,@RequestParam long expectedVersion){CurrentActor a=actors.requireCurrent();if(expectedVersion<0)throw bad();tx.execute(s->{lockGate();auth.requireForUpdate(a.userId(),a.authMode(),projectId,ProjectPermission.MEMBER_MANAGE);if(jdbc.queryForObject("SELECT COUNT(*) FROM project_members WHERE project_id=? AND role='ADMIN'",Long.class,projectId)<=1&&"ADMIN".equals(jdbc.queryForObject("SELECT role FROM project_members WHERE project_id=? AND user_id=?",String.class,projectId,userId)))throw new IdentityAuthorizationException("LAST_PROJECT_ADMIN",409);if(jdbc.update("DELETE FROM project_members WHERE project_id=? AND user_id=? AND version_no=?",projectId,userId,expectedVersion)!=1)throw new IdentityAuthorizationException("VERSION_CONFLICT",409);jdbc.update("UPDATE projects SET permission_version=permission_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?",projectId);return null;});return ApiResponse.ok(null);}
    private void lockGate(){jdbc.queryForObject("SELECT id FROM identity_config_gate WHERE id=? FOR UPDATE",String.class,IdentityConstants.IDENTITY_CONFIG_GATE_ID);}
    private MemberView one(String p,String u){var r=jdbc.query("SELECT u.id,u.display_name,u.status,pm.role,pm.version_no FROM project_members pm JOIN users u ON u.id=pm.user_id WHERE pm.project_id=? AND pm.user_id=?",(x,n)->new MemberView(x.getString(1),x.getString(2),x.getString(3),x.getString(4),x.getLong(5)),p,u);if(r.isEmpty())throw new IdentityAuthorizationException("RESOURCE_NOT_FOUND",404);return r.get(0);}
    private static IdentityAuthorizationException bad(){return new IdentityAuthorizationException("INVALID_REQUEST",400);}
    public record MemberView(String userId,String displayName,String status,String role,long version){} public record MemberChange(String role,long expectedVersion){}
}
